### ISSUE TITLE
Adicionar opção de execução com Docker

### ISSUE THREAD

**Issue by edsoncelio** [edsoncelio/SOpt-telegram-bot#2]
Adicionar opção para executar o *bot* usando *Docker*.
Necessário:
* Adicionar arquivo `Dockerfile` para gerar a imagem com o código do *bot*.
* Adicionar `.dockerignore` para ignorar arquivos desnecessários no *build*

**observação:** atualizar o `Readme.md` com a opção de uso com *Docker*.

**Comment by gustafsilva** [comment]
Posso fazer isso? :smiley:

**Comment by edsoncelio** [comment]
> Posso fazer isso?

Opa, pode sim @gustafsilva, qualquer dúvida pode falar :)
