### ISSUE TITLE
Adicionar testes básicos

### ISSUE THREAD

**Issue by edsoncelio** [edsoncelio/SOpt-telegram-bot#5]

**Comment by tiagocordeiro** [comment]
Posso usar pytest?

**Comment by edsoncelio** [comment]
> @edsoncelio Posso usar pytest?

Opa, pode sim @tiagocordeiro. O código ainda estou refatorando e subindo aos poucos, mas a ideia era usar `pyteste` mesmo.

**Comment by tiagocordeiro** [comment]
Nice
